[package]
name = "comet_assets"
version = "0.1.0"
edition = "2021"

[features]
default = []
diagnostics = []

[dependencies]
comet_app = { workspace = true }
comet_macros = { workspace = true }
comet_log = { workspace = true }
comet_math = { workspace = true }
notify = "6"
anyhow = { workspace = true }
ab_glyph = "0.2.29"
fdsm = "0.8"
fdsm-ttf-parser = "0.2"
fdsm_image = { package = "image", version = "0.25", default-features = false }
guillotiere = "0.6"
image = { workspace = true }
nalgebra = "0.34"
