[package]
name = "comet_ecs"
version = "0.2.0"
edition = "2021"

[dependencies]
component_derive = { path = "./component_derive" }
comet_math = { path = "../comet_math" }
comet_resources = { path = "../comet_resources" }
comet_log = { path = "../comet_log" }

chrono = "0.4"
bit-set = "0.8.0"