[package]
name = "comet_math"
version = "0.1.1"
edition = "2021"

[dependencies]
comet_log = { path = "../comet_log" }
rand = "0.9.0-beta.1"
image = { version = "0.24", default_features = false, features = ["png", "jpeg", "hdr"] }
chrono = "0.4.40"